version: 2
ethernets:
  all-en:
    match:
      name: "en*"
    dhcp4: false
    optional: true
    addresses:
      - 10.69.69.69/24
    gateway4: 10.69.69.1
    nameservers:
      addresses:
        - 1.1.1.1
        - 8.8.8.8