#cloud-config
hostname: daddyvm01
manage_etc_hosts: true

users:
  - name: daddy
    ssh-authorized-keys:
      - <ssh key>
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, docker
    shell: /bin/bash
  - name: root
    ssh-authorized-keys:
      - <ssh key>
    shell: /bin/bash
    lock_passwd: false

ssh_pwauth: true

package_update: true
package_upgrade: true

packages:
  - curl
  - vim
  - ca-certificates
  - gnupg
  - htop
  - net-tools
  - jq

swap:
  filename: none

runcmd:
  - swapoff -a